import { PermitsContent } from "./types";
const cs: PermitsContent = {
  pageTag: "Důležité", pageTitle: "Pobytová povolení ve Švýcarsku",
  pageDesc: "Co musíš vědět, než začneš pracovat – typy povolení, jak je získat a co potřebuješ.",
  introTitle: "🛃 Proč potřebuješ povolení?",
  introText1: "Ve Švýcarsku nestačí jen přijet a začít pracovat. Každý cizinec –",
  introText1Bold: "včetně občanů EU",
  introText2: "– musí mít tzv. pobytové povolení (Ausweis). Díky němu můžeš legálně pracovat, být pojištěný a získat spoustu benefitů – třeba i rekvalifikace zdarma nebo podporu v nezaměstnanosti.",
  euTitle: "🇪🇺 Dobrá zpráva pro občany EU/EFTA",
  euText: "Díky dohodě o volném pohybu", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Typy povolení",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Krátkodobé povolení", color: "yellow", duration: "3–12 měsíců",
      details: ["Smlouva na méně než 12 měsíců", "Nejčastější u práce přes agenturu (temporär)", "Možnost prodloužení", "Vhodné, když ve Švýcarsku začínáš"] },
    { type: "B", name: "Ausweis B", subtitle: "Dlouhodobé povolení", color: "green", duration: "5 let",
      details: ["Smlouva na 12+ měsíců nebo na dobu neurčitou", "Větší svoboda (změna kantonu, ubytování, práce)", "Lepší benefity (rekvalifikace, stabilita, pojištění)", "Nejlepší volba pro dlouhodobý pobyt"] },
    { type: "C", name: "Ausweis C", subtitle: "Trvalý pobyt", color: "blue", duration: "Neomezený",
      details: ["Po 5–10 letech pobytu (záleží na zemi původu)", "Prakticky stejná práva jako Švýcaři", "Volný přístup na trh práce bez omezení", "Nejsilnější forma povolení"] },
    { type: "G", name: "Ausweis G", subtitle: "Přeshraniční pracovník", color: "purple", duration: "5 let",
      details: ["Bydlíš v jiné zemi (Německo, Francie, Itálie...)", "Denně nebo týdně dojíždíš do Švýcarska", "Nehodí se pro ty, kdo se chtějí usadit", "Min. 1× týdně návrat do země bydliště"] },
  ],
  deadlineTitle: "⏰ Kdy to musíš zařídit?",
  deadlineItems: ["📅 Do 14 dnů od příjezdu do Švýcarska", "⚠️ Než začneš oficiálně pracovat", "🏛️ Registrace přes obec (Einwohnerkontrolle) nebo Migrationsamt"],
  deadlineTip: "💡 Některé agentury tě zaregistrují samy, ale vždy si to ověř!",
  docsTitle: "👜 Co budeš potřebovat?",
  docs: [{ icon: "🪪", name: "Pas nebo občanku" }, { icon: "📝", name: "Pracovní smlouvu" }, { icon: "🏠", name: "Potvrzení o ubytování" }, { icon: "📸", name: "Pasovou fotku" }, { icon: "💰", name: "Poplatek (cca 40–60 CHF)" }],
  consequencesTitle: "⚠️ Co se stane, když to nevyřídíš?",
  consequences: [{ icon: "💸", text: "Pokuta", severity: "high" }, { icon: "🚫", text: "Zákaz pobytu", severity: "high" }, { icon: "❌", text: "Ztráta nároků na podporu, pojištění a rekvalifikace", severity: "high" }, { icon: "⚡", text: "Problémy s agenturou nebo zaměstnavatelem", severity: "medium" }],
  renewalTitle: "🔄 Prodloužení povolení", renewalText: "O prodloužení žádáš na", renewalOffice: "obecním úřadě",
  renewalEarliest: "Žádost podej", renewalEarliestBold: "nejdříve 3 měsíce", renewalLatest: "před koncem platnosti", renewalLatestBold: "Nejpozději 2 týdny",
  renewalDocsLabel: "Přílohy k žádosti:", renewalDocs: ["Stávající Ausweis", "Pas nebo občanka", "Potvrzení z úřadu o blížícím se konci platnosti"],
  lostTitle: "❗ Ztráta nebo krádež povolení",
  lostSteps: [{ step: "1", text: "Nahlásíš na policii → dostaneš potvrzení o ztrátě", icon: "🚔" }, { step: "2", text: "S potvrzením, fotkou a pasem jdeš na obec (nebo kanton)", icon: "🏛️" }, { step: "3", text: "Zaplatíš poplatek a vystaví ti nový doklad", icon: "📄" }],
  divorceTitle: "❤️ Rozvod, úmrtí partnera – co dál?",
  divorceIntro: "Pokud jsi ve Švýcarsku díky rodinnému sloučení a partner tě opustí, zemře nebo se rozvedete:",
  euCitizensTitle: "🇪🇺 EU/EFTA občané", euCitizensText: "Můžeš si zažádat o nový Ausweis, pokud:", euCitizensConditions: ["Pracuješ", "Máš dost vlastních financí"],
  thirdCountryTitle: "🌍 Třetizemci", thirdCountryText: "Povolení si můžeš prodloužit, pokud:", thirdCountryConditions: ["Min. 3 roky spolu", "Dobrá integrace (práce, jazyk, bez problémů)", "Osobní důvody (násilí, nemožnost návratu)"],
  keyRuleTitle: "🔒 Nejdůležitější pravidlo", keyRuleText: "Ve Švýcarsku není nic důležitějšího než mít", keyRuleBold: "správné papíry",
  officialTitle: "Oficiální informace", officialDesc: "ch.ch – přehled pobytových povolení", officialLink: "Navštívit →",
  ctaTitle: "Najdi agenturu, která ti vyřídí povolení", ctaDesc: "1 000+ švýcarských personálních agentur s kontakty", ctaButton: "Zobrazit agentury →",
};
export default cs;
