import { PermitsContent } from "./types";
const en: PermitsContent = {
  pageTag: "Important", pageTitle: "Residence Permits in Switzerland",
  pageDesc: "Everything you need to know before you start working – permit types, how to get them, and what you need.",
  introTitle: "🛃 Why do you need a permit?",
  introText1: "In Switzerland, you can't just arrive and start working. Every foreigner –",
  introText1Bold: "including EU citizens",
  introText2: "– must have a so-called residence permit (Ausweis). With it, you can legally work, be insured, and access many benefits – including free retraining or unemployment support.",
  euTitle: "🇪🇺 Good news for EU/EFTA citizens",
  euText: "Thanks to the freedom of movement agreement", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Permit Types",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Short-term permit", color: "yellow", duration: "3–12 months",
      details: ["Contract for less than 12 months", "Most common for agency work (temporär)", "Can be extended", "Ideal when you're just starting in Switzerland"] },
    { type: "B", name: "Ausweis B", subtitle: "Long-term permit", color: "green", duration: "5 years",
      details: ["Contract for 12+ months or indefinite", "More freedom (change canton, housing, job)", "Better benefits (retraining, stability, insurance)", "Best choice for long-term stay"] },
    { type: "C", name: "Ausweis C", subtitle: "Permanent residence", color: "blue", duration: "Unlimited",
      details: ["After 5–10 years of residence (depends on country of origin)", "Practically the same rights as Swiss citizens", "Unrestricted access to the job market", "Strongest form of permit"] },
    { type: "G", name: "Ausweis G", subtitle: "Cross-border commuter", color: "purple", duration: "5 years",
      details: ["You live in another country (Germany, France, Italy...)", "Daily or weekly commute to Switzerland", "Not suitable if you want to settle", "Must return to country of residence at least once a week"] },
  ],
  deadlineTitle: "⏰ When must you arrange it?",
  deadlineItems: ["📅 Within 14 days of arrival in Switzerland", "⚠️ Before you officially start working", "🏛️ Register at the municipality (Einwohnerkontrolle) or Migration Office"],
  deadlineTip: "💡 Some agencies will register you themselves, but always verify!",
  docsTitle: "👜 What will you need?",
  docs: [{ icon: "🪪", name: "Passport or ID card" }, { icon: "📝", name: "Employment contract" }, { icon: "🏠", name: "Proof of accommodation" }, { icon: "📸", name: "Passport photo" }, { icon: "💰", name: "Fee (approx. 40–60 CHF)" }],
  consequencesTitle: "⚠️ What happens if you don't?",
  consequences: [{ icon: "💸", text: "Fine", severity: "high" }, { icon: "🚫", text: "Residence ban", severity: "high" }, { icon: "❌", text: "Loss of benefits, insurance and retraining rights", severity: "high" }, { icon: "⚡", text: "Problems with agency or employer", severity: "medium" }],
  renewalTitle: "🔄 Permit Renewal", renewalText: "Apply for renewal at your", renewalOffice: "local municipality office",
  renewalEarliest: "Submit the application", renewalEarliestBold: "no earlier than 3 months", renewalLatest: "before expiry", renewalLatestBold: "No later than 2 weeks",
  renewalDocsLabel: "Required documents:", renewalDocs: ["Current Ausweis", "Passport or ID card", "Office confirmation of approaching expiry date"],
  lostTitle: "❗ Lost or stolen permit",
  lostSteps: [{ step: "1", text: "Report to police → get a loss confirmation", icon: "🚔" }, { step: "2", text: "Take confirmation, photo and passport to municipality (or canton)", icon: "🏛️" }, { step: "3", text: "Pay the fee and receive a new document", icon: "📄" }],
  divorceTitle: "❤️ Divorce, death of partner – what next?",
  divorceIntro: "If you're in Switzerland through family reunification and your partner leaves, dies, or you divorce:",
  euCitizensTitle: "🇪🇺 EU/EFTA citizens", euCitizensText: "You can apply for a new Ausweis if:", euCitizensConditions: ["You are employed", "You have sufficient personal finances"],
  thirdCountryTitle: "🌍 Third-country nationals", thirdCountryText: "You can extend your permit if:", thirdCountryConditions: ["Min. 3 years together", "Good integration (work, language, no issues)", "Personal reasons (domestic violence, inability to return)"],
  keyRuleTitle: "🔒 The most important rule", keyRuleText: "Nothing in Switzerland is more important than having the", keyRuleBold: "right papers",
  officialTitle: "Official information", officialDesc: "ch.ch – overview of residence permits", officialLink: "Visit →",
  ctaTitle: "Find an agency that handles your permit", ctaDesc: "1,000+ Swiss staffing agencies with contacts", ctaButton: "Show agencies →",
};
export default en;
