import { PermitsContent } from "./types";
const es: PermitsContent = {
  pageTag: "Importante", pageTitle: "Permisos de residencia en Suiza",
  pageDesc: "Todo lo que necesitas saber antes de empezar a trabajar – tipos de permiso, cómo obtenerlos y qué necesitas.",
  introTitle: "🛃 ¿Por qué necesitas un permiso?",
  introText1: "En Suiza no basta con llegar y ponerse a trabajar. Cada extranjero –",
  introText1Bold: "incluidos los ciudadanos de la UE",
  introText2: "– debe tener un permiso de residencia (Ausweis). Con él puedes trabajar legalmente, tener seguro y acceder a muchos beneficios – como recualificación gratuita o prestación por desempleo.",
  euTitle: "🇪🇺 Buenas noticias para ciudadanos UE/AELC", euText: "Gracias al acuerdo de libre circulación", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Tipos de permiso",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Permiso de corta duración", color: "yellow", duration: "3–12 meses", details: ["Contrato de menos de 12 meses", "El más común en trabajo por agencia (temporär)", "Puede prorrogarse", "Ideal para quienes empiezan en Suiza"] },
    { type: "B", name: "Ausweis B", subtitle: "Permiso de larga duración", color: "green", duration: "5 años", details: ["Contrato de 12+ meses o indefinido", "Mayor libertad (cambio de cantón, vivienda, trabajo)", "Mejores prestaciones (recualificación, estabilidad, seguro)", "La mejor opción para estancia prolongada"] },
    { type: "C", name: "Ausweis C", subtitle: "Residencia permanente", color: "blue", duration: "Ilimitado", details: ["Tras 5–10 años de residencia (depende del país de origen)", "Prácticamente los mismos derechos que los suizos", "Acceso libre al mercado laboral", "La forma más sólida de permiso"] },
    { type: "G", name: "Ausweis G", subtitle: "Trabajador transfronterizo", color: "purple", duration: "5 años", details: ["Vives en otro país (Alemania, Francia, Italia...)", "Te desplazas diaria o semanalmente a Suiza", "No apto si quieres establecerte", "Mín. 1× por semana regreso al país de residencia"] },
  ],
  deadlineTitle: "⏰ ¿Cuándo debes gestionarlo?",
  deadlineItems: ["📅 En un plazo de 14 días desde la llegada a Suiza", "⚠️ Antes de empezar a trabajar oficialmente", "🏛️ Registro en el ayuntamiento (Einwohnerkontrolle) o en la Oficina de Migración"],
  deadlineTip: "💡 Algunas agencias te registran ellas mismas, ¡pero compruébalo siempre!",
  docsTitle: "👜 ¿Qué necesitarás?",
  docs: [{ icon: "🪪", name: "Pasaporte o DNI" }, { icon: "📝", name: "Contrato de trabajo" }, { icon: "🏠", name: "Comprobante de alojamiento" }, { icon: "📸", name: "Fotografía de pasaporte" }, { icon: "💰", name: "Tasa (aprox. 40–60 CHF)" }],
  consequencesTitle: "⚠️ ¿Qué pasa si no lo gestionas?",
  consequences: [{ icon: "💸", text: "Multa", severity: "high" }, { icon: "🚫", text: "Prohibición de residencia", severity: "high" }, { icon: "❌", text: "Pérdida de derechos a prestaciones, seguro y recualificación", severity: "high" }, { icon: "⚡", text: "Problemas con la agencia o el empleador", severity: "medium" }],
  renewalTitle: "🔄 Renovación del permiso", renewalText: "La solicitud de renovación se presenta en el", renewalOffice: "ayuntamiento local",
  renewalEarliest: "Presenta la solicitud", renewalEarliestBold: "como máximo 3 meses antes", renewalLatest: "del vencimiento", renewalLatestBold: "Como mínimo 2 semanas antes",
  renewalDocsLabel: "Documentos necesarios:", renewalDocs: ["Ausweis actual", "Pasaporte o DNI", "Confirmación de la oficina sobre el próximo vencimiento"],
  lostTitle: "❗ Pérdida o robo del permiso",
  lostSteps: [{ step: "1", text: "Denuncia en la policía → recibes confirmación de pérdida", icon: "🚔" }, { step: "2", text: "Con la confirmación, foto y pasaporte acude al ayuntamiento (o cantón)", icon: "🏛️" }, { step: "3", text: "Paga la tasa y recibe un nuevo documento", icon: "📄" }],
  divorceTitle: "❤️ Divorcio, fallecimiento del cónyuge – ¿y ahora qué?",
  divorceIntro: "Si estás en Suiza por reagrupación familiar y tu pareja te deja, fallece o os divorciáis:",
  euCitizensTitle: "🇪🇺 Ciudadanos UE/AELC", euCitizensText: "Puedes solicitar un nuevo Ausweis si:", euCitizensConditions: ["Trabajas", "Tienes recursos económicos suficientes"],
  thirdCountryTitle: "🌍 Ciudadanos de terceros países", thirdCountryText: "Puedes prorrogar el permiso si:", thirdCountryConditions: ["Mín. 3 años juntos", "Buena integración (trabajo, idioma, sin problemas)", "Motivos personales (violencia, imposibilidad de regreso)"],
  keyRuleTitle: "🔒 La regla más importante", keyRuleText: "En Suiza no hay nada más importante que tener los", keyRuleBold: "papeles en regla",
  officialTitle: "Información oficial", officialDesc: "ch.ch – resumen de permisos de residencia", officialLink: "Visitar →",
  ctaTitle: "Encuentra una agencia que te gestione el permiso", ctaDesc: "Más de 1.000 agencias de empleo suizas con contactos", ctaButton: "Mostrar agencias →",
};
export default es;
