import { PermitsContent } from "./types";
const hu: PermitsContent = {
  pageTag: "Fontos", pageTitle: "Tartózkodási engedélyek Svájcban",
  pageDesc: "Minden, amit tudnod kell a munkakezdés előtt – engedélytípusok, hogyan szerezheted meg őket és mire van szükséged.",
  introTitle: "🛃 Miért van szükséged engedélyre?",
  introText1: "Svájcban nem elég egyszerűen megérkezni és elkezdeni dolgozni. Minden külföldi –",
  introText1Bold: "beleértve az EU állampolgárokat is",
  introText2: "– rendelkeznie kell tartózkodási engedéllyel (Ausweis). Ezzel legálisan dolgozhatsz, biztosítva leszel, és számos kedvezményt kaphatsz – például ingyenes átképzést vagy munkanélküli segélyt.",
  euTitle: "🇪🇺 Jó hír az EU/EFTA állampolgároknak", euText: "A szabad mozgásról szóló megállapodásnak köszönhetően", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Engedélytípusok",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Rövid távú engedély", color: "yellow", duration: "3–12 hónap", details: ["12 hónapnál rövidebb szerződés", "A leggyakoribb ügynökségi munkánál (temporär)", "Meghosszabbítható", "Ideális, ha most kezdesz Svájcban"] },
    { type: "B", name: "Ausweis B", subtitle: "Hosszú távú engedély", color: "green", duration: "5 év", details: ["12+ hónapos vagy határozatlan idejű szerződés", "Több szabadság (kantonváltás, lakás, munka)", "Jobb juttatások (átképzés, stabilitás, biztosítás)", "A legjobb választás hosszú tartózkodáshoz"] },
    { type: "C", name: "Ausweis C", subtitle: "Állandó letelepedési engedély", color: "blue", duration: "Korlátlan", details: ["5–10 év tartózkodás után (származási országtól függ)", "Gyakorlatilag ugyanazok a jogok, mint a svájciaké", "Szabad hozzáférés a munkaerőpiachoz", "Az engedély legerősebb formája"] },
    { type: "G", name: "Ausweis G", subtitle: "Határon átnyúló ingázó", color: "purple", duration: "5 év", details: ["Másik országban laksz (Németország, Franciaország, Olaszország...)", "Napi vagy heti ingázás Svájcba", "Nem alkalmas, ha le akarsz telepedni", "Min. hetente 1× visszatérés a lakóhely országába"] },
  ],
  deadlineTitle: "⏰ Mikor kell elintézned?",
  deadlineItems: ["📅 A Svájcba érkezéstől számított 14 napon belül", "⚠️ Mielőtt hivatalosan elkezdenél dolgozni", "🏛️ Regisztráció az önkormányzatnál (Einwohnerkontrolle) vagy a Migrációs Hivatalnál"],
  deadlineTip: "💡 Egyes ügynökségek maguk regisztrálnak téged, de mindig ellenőrizd!",
  docsTitle: "👜 Mire lesz szükséged?",
  docs: [{ icon: "🪪", name: "Útlevél vagy személyi igazolvány" }, { icon: "📝", name: "Munkaszerződés" }, { icon: "🏠", name: "Lakhatás igazolása" }, { icon: "📸", name: "Igazolványkép" }, { icon: "💰", name: "Illeték (kb. 40–60 CHF)" }],
  consequencesTitle: "⚠️ Mi történik, ha nem intézed el?",
  consequences: [{ icon: "💸", text: "Bírság", severity: "high" }, { icon: "🚫", text: "Tartózkodási tilalom", severity: "high" }, { icon: "❌", text: "A juttatásokhoz, biztosításhoz és átképzéshez való jog elvesztése", severity: "high" }, { icon: "⚡", text: "Problémák az ügynökséggel vagy a munkáltatóval", severity: "medium" }],
  renewalTitle: "🔄 Az engedély meghosszabbítása", renewalText: "A meghosszabbítási kérelmet az", renewalOffice: "önkormányzathoz nyújtod be",
  renewalEarliest: "Nyújtsd be a kérelmet", renewalEarliestBold: "legkorábban 3 hónappal", renewalLatest: "a lejárat előtt", renewalLatestBold: "Legkésőbb 2 héttel",
  renewalDocsLabel: "Szükséges dokumentumok:", renewalDocs: ["Jelenlegi Ausweis", "Útlevél vagy személyi igazolvány", "Hivatal igazolása a közelgő lejáratról"],
  lostTitle: "❗ Az engedély elvesztése vagy ellopása",
  lostSteps: [{ step: "1", text: "Bejelentés a rendőrségen → elvesztési igazolást kapsz", icon: "🚔" }, { step: "2", text: "Az igazolással, fotóval és útlevéllel menj az önkormányzathoz (vagy kantonhoz)", icon: "🏛️" }, { step: "3", text: "Fizesd be az illetéket és megkapod az új dokumentumot", icon: "📄" }],
  divorceTitle: "❤️ Válás, a partner halála – mi a következő lépés?",
  divorceIntro: "Ha családegyesítés révén vagy Svájcban és a partnered elhagy, meghal vagy elváltok:",
  euCitizensTitle: "🇪🇺 EU/EFTA állampolgárok", euCitizensText: "Kérelmezhetsz új Ausweis-t, ha:", euCitizensConditions: ["Dolgozol", "Elegendő saját pénzügyi forrásokkal rendelkezel"],
  thirdCountryTitle: "🌍 Harmadik országbeli állampolgárok", thirdCountryText: "Meghosszabbíthatod az engedélyt, ha:", thirdCountryConditions: ["Min. 3 év együttélés", "Jó integráció (munka, nyelv, problémamentes)", "Személyes okok (erőszak, visszatérés lehetetlensége)"],
  keyRuleTitle: "🔒 A legfontosabb szabály", keyRuleText: "Svájcban semmi sem fontosabb, mint hogy meglegyen a", keyRuleBold: "megfelelő papírod",
  officialTitle: "Hivatalos információk", officialDesc: "ch.ch – tartózkodási engedélyek áttekintése", officialLink: "Meglátogatás →",
  ctaTitle: "Találj ügynökséget, amely elintézi az engedélyedet", ctaDesc: "Több mint 1000 svájci munkaerő-közvetítő elérhetőségekkel", ctaButton: "Ügynökségek megjelenítése →",
};
export default hu;
