import { PermitsContent } from "./types";
const it: PermitsContent = {
  pageTag: "Importante", pageTitle: "Permessi di soggiorno in Svizzera",
  pageDesc: "Tutto quello che devi sapere prima di iniziare a lavorare – tipi di permesso, come ottenerli e cosa ti serve.",
  introTitle: "🛃 Perché hai bisogno di un permesso?",
  introText1: "In Svizzera non basta arrivare e iniziare a lavorare. Ogni straniero –",
  introText1Bold: "compresi i cittadini UE",
  introText2: "– deve avere un permesso di soggiorno (Ausweis). Con esso puoi lavorare legalmente, avere un'assicurazione e accedere a molti vantaggi – come la riqualificazione gratuita o l'indennità di disoccupazione.",
  euTitle: "🇪🇺 Buone notizie per i cittadini UE/AELS", euText: "Grazie all'accordo sulla libera circolazione", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Tipi di permesso",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Permesso a breve termine", color: "yellow", duration: "3–12 mesi", details: ["Contratto inferiore a 12 mesi", "Il più comune per il lavoro tramite agenzia (temporär)", "Può essere prolungato", "Ideale per chi inizia in Svizzera"] },
    { type: "B", name: "Ausweis B", subtitle: "Permesso a lungo termine", color: "green", duration: "5 anni", details: ["Contratto di 12+ mesi o a tempo indeterminato", "Maggiore libertà (cambio cantone, alloggio, lavoro)", "Migliori benefici (riqualificazione, stabilità, assicurazione)", "La scelta migliore per un soggiorno lungo"] },
    { type: "C", name: "Ausweis C", subtitle: "Residenza permanente", color: "blue", duration: "Illimitato", details: ["Dopo 5–10 anni di residenza (dipende dal paese di origine)", "Praticamente gli stessi diritti degli svizzeri", "Accesso libero al mercato del lavoro", "La forma più forte di permesso"] },
    { type: "G", name: "Ausweis G", subtitle: "Lavoratore frontaliero", color: "purple", duration: "5 anni", details: ["Vivi in un altro paese (Germania, Francia, Italia...)", "Fai il pendolare giornalmente o settimanalmente in Svizzera", "Non adatto se vuoi stabilirti", "Min. 1× a settimana ritorno nel paese di residenza"] },
  ],
  deadlineTitle: "⏰ Quando devi occupartene?",
  deadlineItems: ["📅 Entro 14 giorni dall'arrivo in Svizzera", "⚠️ Prima di iniziare ufficialmente a lavorare", "🏛️ Registrazione al comune (Einwohnerkontrolle) o all'Ufficio Migrazione"],
  deadlineTip: "💡 Alcune agenzie ti registrano da sole, ma verifica sempre!",
  docsTitle: "👜 Cosa ti servirà?",
  docs: [{ icon: "🪪", name: "Passaporto o carta d'identità" }, { icon: "📝", name: "Contratto di lavoro" }, { icon: "🏠", name: "Prova di alloggio" }, { icon: "📸", name: "Fototessera" }, { icon: "💰", name: "Tassa (ca. 40–60 CHF)" }],
  consequencesTitle: "⚠️ Cosa succede se non lo fai?",
  consequences: [{ icon: "💸", text: "Multa", severity: "high" }, { icon: "🚫", text: "Divieto di soggiorno", severity: "high" }, { icon: "❌", text: "Perdita dei diritti a prestazioni, assicurazione e riqualificazione", severity: "high" }, { icon: "⚡", text: "Problemi con l'agenzia o il datore di lavoro", severity: "medium" }],
  renewalTitle: "🔄 Rinnovo del permesso", renewalText: "La domanda di rinnovo si presenta al", renewalOffice: "comune di residenza",
  renewalEarliest: "Presenta la domanda", renewalEarliestBold: "al più presto 3 mesi", renewalLatest: "prima della scadenza", renewalLatestBold: "Al più tardi 2 settimane",
  renewalDocsLabel: "Documenti necessari:", renewalDocs: ["Ausweis attuale", "Passaporto o carta d'identità", "Conferma dell'ufficio sull'imminente scadenza"],
  lostTitle: "❗ Perdita o furto del permesso",
  lostSteps: [{ step: "1", text: "Denuncia alla polizia → ottieni conferma della perdita", icon: "🚔" }, { step: "2", text: "Con la conferma, la foto e il passaporto vai al comune (o cantone)", icon: "🏛️" }, { step: "3", text: "Paga la tassa e ricevi un nuovo documento", icon: "📄" }],
  divorceTitle: "❤️ Divorzio, morte del partner – e poi?",
  divorceIntro: "Se sei in Svizzera per ricongiungimento familiare e il tuo partner ti lascia, muore o divorziate:",
  euCitizensTitle: "🇪🇺 Cittadini UE/AELS", euCitizensText: "Puoi richiedere un nuovo Ausweis se:", euCitizensConditions: ["Lavori", "Hai risorse finanziarie sufficienti"],
  thirdCountryTitle: "🌍 Cittadini di paesi terzi", thirdCountryText: "Puoi prolungare il permesso se:", thirdCountryConditions: ["Min. 3 anni insieme", "Buona integrazione (lavoro, lingua, nessun problema)", "Motivi personali (violenza, impossibilità di ritorno)"],
  keyRuleTitle: "🔒 La regola più importante", keyRuleText: "In Svizzera niente è più importante di avere i", keyRuleBold: "documenti in regola",
  officialTitle: "Informazioni ufficiali", officialDesc: "ch.ch – panoramica dei permessi di soggiorno", officialLink: "Visita →",
  ctaTitle: "Trova un'agenzia che ti gestisca il permesso", ctaDesc: "Oltre 1.000 agenzie di lavoro svizzere con contatti", ctaButton: "Mostra agenzie →",
};
export default it;
