import { PermitsContent } from "./types";
const pl: PermitsContent = {
  pageTag: "Ważne", pageTitle: "Pozwolenia pobytowe w Szwajcarii",
  pageDesc: "Wszystko, co musisz wiedzieć przed rozpoczęciem pracy – rodzaje pozwoleń, jak je uzyskać i co jest potrzebne.",
  introTitle: "🛃 Dlaczego potrzebujesz pozwolenia?",
  introText1: "W Szwajcarii nie wystarczy po prostu przyjechać i zacząć pracować. Każdy obcokrajowiec –",
  introText1Bold: "łącznie z obywatelami UE",
  introText2: "– musi posiadać tzw. pozwolenie pobytowe (Ausweis). Dzięki niemu możesz legalnie pracować, mieć ubezpieczenie i korzystać z wielu świadczeń – np. darmowych przekwalifikowań czy zasiłku dla bezrobotnych.",
  euTitle: "🇪🇺 Dobra wiadomość dla obywateli UE/EFTA",
  euText: "Dzięki umowie o swobodnym przepływie osób", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Rodzaje pozwoleń",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Pozwolenie krótkoterminowe", color: "yellow", duration: "3–12 miesięcy",
      details: ["Umowa na mniej niż 12 miesięcy", "Najczęstsze przy pracy przez agencję (temporär)", "Możliwość przedłużenia", "Idealne na początek w Szwajcarii"] },
    { type: "B", name: "Ausweis B", subtitle: "Pozwolenie długoterminowe", color: "green", duration: "5 lat",
      details: ["Umowa na 12+ miesięcy lub na czas nieokreślony", "Większa swoboda (zmiana kantonu, mieszkania, pracy)", "Lepsze świadczenia (przekwalifikowanie, stabilność, ubezpieczenie)", "Najlepszy wybór na dłuższy pobyt"] },
    { type: "C", name: "Ausweis C", subtitle: "Pobyt stały", color: "blue", duration: "Bez ograniczeń",
      details: ["Po 5–10 latach pobytu (zależy od kraju pochodzenia)", "Praktycznie takie same prawa jak Szwajcarzy", "Swobodny dostęp do rynku pracy", "Najsilniejsza forma pozwolenia"] },
    { type: "G", name: "Ausweis G", subtitle: "Pracownik transgraniczny", color: "purple", duration: "5 lat",
      details: ["Mieszkasz w innym kraju (Niemcy, Francja, Włochy...)", "Codziennie lub tygodniowo dojeżdżasz do Szwajcarii", "Nie nadaje się, jeśli chcesz się osiedlić", "Min. 1× tygodniowo powrót do kraju zamieszkania"] },
  ],
  deadlineTitle: "⏰ Kiedy musisz to załatwić?",
  deadlineItems: ["📅 W ciągu 14 dni od przyjazdu do Szwajcarii", "⚠️ Zanim oficjalnie zaczniesz pracować", "🏛️ Rejestracja w gminie (Einwohnerkontrolle) lub Urzędzie Migracyjnym"],
  deadlineTip: "💡 Niektóre agencje zarejestrują cię same, ale zawsze to sprawdź!",
  docsTitle: "👜 Co będziesz potrzebować?",
  docs: [{ icon: "🪪", name: "Paszport lub dowód osobisty" }, { icon: "📝", name: "Umowę o pracę" }, { icon: "🏠", name: "Potwierdzenie zakwaterowania" }, { icon: "📸", name: "Zdjęcie paszportowe" }, { icon: "💰", name: "Opłata (ok. 40–60 CHF)" }],
  consequencesTitle: "⚠️ Co się stanie, jeśli tego nie załatwisz?",
  consequences: [{ icon: "💸", text: "Grzywna", severity: "high" }, { icon: "🚫", text: "Zakaz pobytu", severity: "high" }, { icon: "❌", text: "Utrata praw do świadczeń, ubezpieczenia i przekwalifikowania", severity: "high" }, { icon: "⚡", text: "Problemy z agencją lub pracodawcą", severity: "medium" }],
  renewalTitle: "🔄 Przedłużenie pozwolenia", renewalText: "O przedłużenie wnioskujesz w", renewalOffice: "urzędzie gminy",
  renewalEarliest: "Złóż wniosek", renewalEarliestBold: "najwcześniej 3 miesiące", renewalLatest: "przed końcem ważności", renewalLatestBold: "Najpóźniej 2 tygodnie",
  renewalDocsLabel: "Wymagane dokumenty:", renewalDocs: ["Aktualny Ausweis", "Paszport lub dowód osobisty", "Potwierdzenie z urzędu o zbliżającym się końcu ważności"],
  lostTitle: "❗ Utrata lub kradzież pozwolenia",
  lostSteps: [{ step: "1", text: "Zgłoś na policji → otrzymasz potwierdzenie utraty", icon: "🚔" }, { step: "2", text: "Z potwierdzeniem, zdjęciem i paszportem idź do gminy (lub kantonu)", icon: "🏛️" }, { step: "3", text: "Zapłać opłatę i otrzymaj nowy dokument", icon: "📄" }],
  divorceTitle: "❤️ Rozwód, śmierć partnera – co dalej?",
  divorceIntro: "Jeśli jesteś w Szwajcarii dzięki łączeniu rodzin i partner cię opuści, umrze lub się rozwiedziesz:",
  euCitizensTitle: "🇪🇺 Obywatele UE/EFTA", euCitizensText: "Możesz złożyć wniosek o nowy Ausweis, jeśli:", euCitizensConditions: ["Pracujesz", "Masz wystarczające środki finansowe"],
  thirdCountryTitle: "🌍 Obywatele krajów trzecich", thirdCountryText: "Możesz przedłużyć pozwolenie, jeśli:", thirdCountryConditions: ["Min. 3 lata razem", "Dobra integracja (praca, język, brak problemów)", "Powody osobiste (przemoc, brak możliwości powrotu)"],
  keyRuleTitle: "🔒 Najważniejsza zasada", keyRuleText: "Nic w Szwajcarii nie jest ważniejsze niż posiadanie", keyRuleBold: "odpowiednich dokumentów",
  officialTitle: "Oficjalne informacje", officialDesc: "ch.ch – przegląd pozwoleń pobytowych", officialLink: "Odwiedź →",
  ctaTitle: "Znajdź agencję, która załatwi ci pozwolenie", ctaDesc: "Ponad 1000 szwajcarskich agencji personalnych z kontaktami", ctaButton: "Pokaż agencje →",
};
export default pl;
