import { PermitsContent } from "./types";
const pt: PermitsContent = {
  pageTag: "Importante", pageTitle: "Autorizações de residência na Suíça",
  pageDesc: "Tudo o que precisas de saber antes de começar a trabalhar – tipos de autorização, como obtê-las e o que precisas.",
  introTitle: "🛃 Porque precisas de uma autorização?",
  introText1: "Na Suíça não basta chegar e começar a trabalhar. Cada estrangeiro –",
  introText1Bold: "incluindo cidadãos da UE",
  introText2: "– deve ter uma autorização de residência (Ausweis). Com ela podes trabalhar legalmente, ter seguro e aceder a muitos benefícios – como requalificação gratuita ou subsídio de desemprego.",
  euTitle: "🇪🇺 Boas notícias para cidadãos UE/EFTA", euText: "Graças ao acordo de livre circulação", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Tipos de autorização",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Autorização de curta duração", color: "yellow", duration: "3–12 meses", details: ["Contrato inferior a 12 meses", "Mais comum no trabalho por agência (temporär)", "Pode ser prolongada", "Ideal para quem está a começar na Suíça"] },
    { type: "B", name: "Ausweis B", subtitle: "Autorização de longa duração", color: "green", duration: "5 anos", details: ["Contrato de 12+ meses ou por tempo indeterminado", "Mais liberdade (mudança de cantão, alojamento, trabalho)", "Melhores benefícios (requalificação, estabilidade, seguro)", "Melhor escolha para estadia prolongada"] },
    { type: "C", name: "Ausweis C", subtitle: "Residência permanente", color: "blue", duration: "Ilimitada", details: ["Após 5–10 anos de residência (depende do país de origem)", "Praticamente os mesmos direitos que os suíços", "Acesso livre ao mercado de trabalho", "A forma mais forte de autorização"] },
    { type: "G", name: "Ausweis G", subtitle: "Trabalhador transfronteiriço", color: "purple", duration: "5 anos", details: ["Vives noutro país (Alemanha, França, Itália...)", "Deslocas-te diária ou semanalmente para a Suíça", "Não adequado se queres estabelecer-te", "Mín. 1× por semana regresso ao país de residência"] },
  ],
  deadlineTitle: "⏰ Quando tens de tratar disto?",
  deadlineItems: ["📅 Até 14 dias após a chegada à Suíça", "⚠️ Antes de começar oficialmente a trabalhar", "🏛️ Registo na junta de freguesia (Einwohnerkontrolle) ou Serviço de Migração"],
  deadlineTip: "💡 Algumas agências registam-te elas próprias, mas verifica sempre!",
  docsTitle: "👜 O que vais precisar?",
  docs: [{ icon: "🪪", name: "Passaporte ou cartão de cidadão" }, { icon: "📝", name: "Contrato de trabalho" }, { icon: "🏠", name: "Comprovativo de alojamento" }, { icon: "📸", name: "Fotografia tipo passe" }, { icon: "💰", name: "Taxa (aprox. 40–60 CHF)" }],
  consequencesTitle: "⚠️ O que acontece se não tratares?",
  consequences: [{ icon: "💸", text: "Multa", severity: "high" }, { icon: "🚫", text: "Proibição de residência", severity: "high" }, { icon: "❌", text: "Perda de direitos a apoios, seguro e requalificação", severity: "high" }, { icon: "⚡", text: "Problemas com a agência ou empregador", severity: "medium" }],
  renewalTitle: "🔄 Renovação da autorização", renewalText: "O pedido de renovação faz-se na", renewalOffice: "junta de freguesia local",
  renewalEarliest: "Submete o pedido", renewalEarliestBold: "no máximo 3 meses antes", renewalLatest: "do fim da validade", renewalLatestBold: "No mínimo 2 semanas antes",
  renewalDocsLabel: "Documentos necessários:", renewalDocs: ["Ausweis atual", "Passaporte ou cartão de cidadão", "Confirmação do serviço sobre a aproximação do fim da validade"],
  lostTitle: "❗ Perda ou roubo da autorização",
  lostSteps: [{ step: "1", text: "Reporta à polícia → recebes confirmação da perda", icon: "🚔" }, { step: "2", text: "Com a confirmação, foto e passaporte vai à junta (ou cantão)", icon: "🏛️" }, { step: "3", text: "Paga a taxa e recebes um novo documento", icon: "📄" }],
  divorceTitle: "❤️ Divórcio, morte do parceiro – e agora?",
  divorceIntro: "Se estás na Suíça por reunificação familiar e o teu parceiro te deixa, morre ou vocês divorciam-se:",
  euCitizensTitle: "🇪🇺 Cidadãos UE/EFTA", euCitizensText: "Podes pedir um novo Ausweis se:", euCitizensConditions: ["Trabalhas", "Tens recursos financeiros suficientes"],
  thirdCountryTitle: "🌍 Cidadãos de países terceiros", thirdCountryText: "Podes prolongar a autorização se:", thirdCountryConditions: ["Mín. 3 anos juntos", "Boa integração (trabalho, língua, sem problemas)", "Motivos pessoais (violência, impossibilidade de regresso)"],
  keyRuleTitle: "🔒 A regra mais importante", keyRuleText: "Na Suíça nada é mais importante do que ter os", keyRuleBold: "documentos em ordem",
  officialTitle: "Informações oficiais", officialDesc: "ch.ch – visão geral das autorizações de residência", officialLink: "Visitar →",
  ctaTitle: "Encontra uma agência que trate da tua autorização", ctaDesc: "Mais de 1.000 agências de trabalho suíças com contactos", ctaButton: "Mostrar agências →",
};
export default pt;
