import { PermitsContent } from "./types";
const ro: PermitsContent = {
  pageTag: "Important", pageTitle: "Permise de ședere în Elveția",
  pageDesc: "Tot ce trebuie să știi înainte de a începe munca – tipuri de permise, cum le obții și ce ai nevoie.",
  introTitle: "🛃 De ce ai nevoie de un permis?",
  introText1: "În Elveția nu poți pur și simplu să vii și să începi să lucrezi. Fiecare străin –",
  introText1Bold: "inclusiv cetățenii UE",
  introText2: "– trebuie să aibă un permis de ședere (Ausweis). Cu el poți lucra legal, ai asigurare și beneficiezi de multe avantaje – de exemplu, recalificare gratuită sau ajutor de șomaj.",
  euTitle: "🇪🇺 Veste bună pentru cetățenii UE/AELS", euText: "Datorită acordului privind libera circulație", euAgreement: "(Freizügigkeitsabkommen)",
  permitTypesTitle: "📋 Tipuri de permise",
  permits: [
    { type: "L", name: "Ausweis L", subtitle: "Permis pe termen scurt", color: "yellow", duration: "3–12 luni", details: ["Contract pe mai puțin de 12 luni", "Cel mai frecvent la munca prin agenție (temporär)", "Poate fi prelungit", "Ideal când abia începi în Elveția"] },
    { type: "B", name: "Ausweis B", subtitle: "Permis pe termen lung", color: "green", duration: "5 ani", details: ["Contract pe 12+ luni sau pe perioadă nedeterminată", "Mai multă libertate (schimbare canton, locuință, muncă)", "Beneficii mai bune (recalificare, stabilitate, asigurare)", "Cea mai bună alegere pentru ședere pe termen lung"] },
    { type: "C", name: "Ausweis C", subtitle: "Reședință permanentă", color: "blue", duration: "Nelimitat", details: ["După 5–10 ani de ședere (depinde de țara de origine)", "Practic aceleași drepturi ca elvețienii", "Acces liber pe piața muncii", "Cea mai puternică formă de permis"] },
    { type: "G", name: "Ausweis G", subtitle: "Lucrător transfrontalier", color: "purple", duration: "5 ani", details: ["Locuiești în altă țară (Germania, Franța, Italia...)", "Faci naveta zilnic sau săptămânal în Elveția", "Nu e potrivit dacă vrei să te stabilești", "Min. 1× pe săptămână întoarcere în țara de reședință"] },
  ],
  deadlineTitle: "⏰ Când trebuie să te ocupi de asta?",
  deadlineItems: ["📅 În termen de 14 zile de la sosirea în Elveția", "⚠️ Înainte de a începe oficial munca", "🏛️ Înregistrare la primărie (Einwohnerkontrolle) sau Oficiul de Migrație"],
  deadlineTip: "💡 Unele agenții te înregistrează singure, dar verifică întotdeauna!",
  docsTitle: "👜 Ce vei avea nevoie?",
  docs: [{ icon: "🪪", name: "Pașaport sau carte de identitate" }, { icon: "📝", name: "Contract de muncă" }, { icon: "🏠", name: "Dovada cazării" }, { icon: "📸", name: "Fotografie de pașaport" }, { icon: "💰", name: "Taxă (aprox. 40–60 CHF)" }],
  consequencesTitle: "⚠️ Ce se întâmplă dacă nu te ocupi?",
  consequences: [{ icon: "💸", text: "Amendă", severity: "high" }, { icon: "🚫", text: "Interdicție de ședere", severity: "high" }, { icon: "❌", text: "Pierderea drepturilor la ajutoare, asigurare și recalificare", severity: "high" }, { icon: "⚡", text: "Probleme cu agenția sau angajatorul", severity: "medium" }],
  renewalTitle: "🔄 Prelungirea permisului", renewalText: "Cererea de prelungire se depune la", renewalOffice: "primăria locală",
  renewalEarliest: "Depune cererea", renewalEarliestBold: "cel mai devreme cu 3 luni", renewalLatest: "înainte de expirare", renewalLatestBold: "Cel mai târziu cu 2 săptămâni",
  renewalDocsLabel: "Documente necesare:", renewalDocs: ["Ausweis-ul curent", "Pașaport sau carte de identitate", "Confirmare de la birou privind expirarea apropiată"],
  lostTitle: "❗ Pierderea sau furtul permisului",
  lostSteps: [{ step: "1", text: "Raportezi la poliție → primești confirmare de pierdere", icon: "🚔" }, { step: "2", text: "Cu confirmarea, fotografia și pașaportul mergi la primărie (sau canton)", icon: "🏛️" }, { step: "3", text: "Plătești taxa și primești un document nou", icon: "📄" }],
  divorceTitle: "❤️ Divorț, decesul partenerului – ce urmează?",
  divorceIntro: "Dacă ești în Elveția prin reunificarea familiei și partenerul te părăsește, moare sau divorțați:",
  euCitizensTitle: "🇪🇺 Cetățeni UE/AELS", euCitizensText: "Poți solicita un Ausweis nou dacă:", euCitizensConditions: ["Lucrezi", "Ai suficiente resurse financiare proprii"],
  thirdCountryTitle: "🌍 Cetățeni din țări terțe", thirdCountryText: "Poți prelungi permisul dacă:", thirdCountryConditions: ["Min. 3 ani împreună", "Bună integrare (muncă, limbă, fără probleme)", "Motive personale (violență, imposibilitate de întoarcere)"],
  keyRuleTitle: "🔒 Cea mai importantă regulă", keyRuleText: "Nimic în Elveția nu este mai important decât a avea", keyRuleBold: "actele în regulă",
  officialTitle: "Informații oficiale", officialDesc: "ch.ch – prezentare generală a permiselor de ședere", officialLink: "Vizitează →",
  ctaTitle: "Găsește o agenție care îți rezolvă permisul", ctaDesc: "Peste 1.000 de agenții de personal elvețiene cu date de contact", ctaButton: "Arată agențiile →",
};
export default ro;
