export interface PermitsContent {
  pageTag: string;
  pageTitle: string;
  pageDesc: string;
  introTitle: string;
  introText1: string;
  introText1Bold: string;
  introText2: string;
  euTitle: string;
  euText: string;
  euAgreement: string;
  permitTypesTitle: string;
  permits: { type: string; name: string; subtitle: string; color: string; duration: string; details: string[]; }[];
  deadlineTitle: string;
  deadlineItems: string[];
  deadlineTip: string;
  docsTitle: string;
  docs: { icon: string; name: string }[];
  consequencesTitle: string;
  consequences: { icon: string; text: string; severity: string }[];
  renewalTitle: string;
  renewalText: string;
  renewalOffice: string;
  renewalEarliest: string;
  renewalEarliestBold: string;
  renewalLatest: string;
  renewalLatestBold: string;
  renewalDocsLabel: string;
  renewalDocs: string[];
  lostTitle: string;
  lostSteps: { step: string; text: string; icon: string }[];
  divorceTitle: string;
  divorceIntro: string;
  euCitizensTitle: string;
  euCitizensText: string;
  euCitizensConditions: string[];
  thirdCountryTitle: string;
  thirdCountryText: string;
  thirdCountryConditions: string[];
  keyRuleTitle: string;
  keyRuleText: string;
  keyRuleBold: string;
  officialTitle: string;
  officialDesc: string;
  officialLink: string;
  ctaTitle: string;
  ctaDesc: string;
  ctaButton: string;
}
