-- Woker Pivot v2.0 — Gmail OAuth + AI agent matching
-- Phase 1 schema: oauth tokens, member config, daily matches, send log

-- 1. Encrypted OAuth tokens for Gmail (and later Outlook)
create table if not exists public.email_oauth_tokens (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null references auth.users(id) on delete cascade,
  provider        text not null check (provider in ('gmail','outlook')),
  email           text not null,
  refresh_token   text not null,                    -- encrypted via pgsodium
  access_token    text,
  expires_at      timestamptz,
  scopes          text[],
  connected_at    timestamptz not null default now(),
  last_used_at    timestamptz,
  revoked         boolean not null default false,

  unique (member_id, provider)
);

create index if not exists idx_oauth_tokens_member on public.email_oauth_tokens(member_id);

-- 2. Member's agent configuration (preferences for daily matching)
create table if not exists public.member_agent_config (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null unique references auth.users(id) on delete cascade,
  active          boolean not null default true,
  daily_limit     integer not null default 3 check (daily_limit between 0 and 50),
  auto_send       boolean not null default false,
  positions       text[] not null default '{}',
  locations       text[] not null default '{}',
  languages       text[] not null default array['de'],
  salary_min_chf  integer,
  cv_pdf_url      text,
  motivak_base    text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_agent_config_active on public.member_agent_config(active) where active = true;

-- 3. Daily matches generated by cron job
create table if not exists public.daily_matches (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null references auth.users(id) on delete cascade,
  job_url         text,
  company         text not null,
  position        text not null,
  location        text,
  match_score     integer check (match_score between 0 and 100),
  match_reasoning text,
  draft_subject   text,
  draft_body      text,
  generated_at    timestamptz not null default now(),
  status          text not null default 'pending' check (status in ('pending','sent','skipped','edited','expired')),
  sent_at         timestamptz
);

create index if not exists idx_daily_matches_member_status on public.daily_matches(member_id, status);
create index if not exists idx_daily_matches_generated on public.daily_matches(generated_at desc);

-- 4. Email send log (for audit + reply tracking)
create table if not exists public.email_send_log (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null references auth.users(id) on delete cascade,
  match_id        uuid references public.daily_matches(id) on delete set null,
  recipient_email text not null,
  subject         text,
  provider        text not null check (provider in ('gmail','outlook')),
  message_id      text,
  thread_id       text,
  sent_at         timestamptz not null default now(),
  opened          boolean not null default false,
  replied         boolean not null default false
);

create index if not exists idx_send_log_member on public.email_send_log(member_id, sent_at desc);
create index if not exists idx_send_log_thread on public.email_send_log(thread_id);

-- RLS: lock down all tables to service_role + member's own rows only
alter table public.email_oauth_tokens enable row level security;
alter table public.member_agent_config enable row level security;
alter table public.daily_matches enable row level security;
alter table public.email_send_log enable row level security;

-- Members can read/update their own config
create policy "members read own oauth"
  on public.email_oauth_tokens for select
  using (auth.uid() = member_id);

create policy "members read own agent config"
  on public.member_agent_config for select
  using (auth.uid() = member_id);

create policy "members update own agent config"
  on public.member_agent_config for update
  using (auth.uid() = member_id);

create policy "members read own matches"
  on public.daily_matches for select
  using (auth.uid() = member_id);

create policy "members update own matches"
  on public.daily_matches for update
  using (auth.uid() = member_id);

create policy "members read own send log"
  on public.email_send_log for select
  using (auth.uid() = member_id);
