import type { WookyFieldMeta, WookyChoiceOption } from './types'

// ===== Reusable option sets =====

const CEFR_LEVELS: WookyChoiceOption[] = [
  { value: 'Začátečník', label: 'Začátečník', hint: 'Pár slov, základní fráze' },
  { value: 'A1', label: 'A1', hint: 'Velmi základní' },
  { value: 'A2', label: 'A2', hint: 'Základy domluvy' },
  { value: 'B1', label: 'B1', hint: 'Střední — domluvím se' },
  { value: 'B2', label: 'B2', hint: 'Pokročilý — práce v jazyce' },
  { value: 'C1', label: 'C1', hint: 'Velmi pokročilý' },
  { value: 'C2', label: 'C2', hint: 'Téměř rodilý mluvčí' },
  { value: 'Mateřský', label: 'Mateřský', hint: 'Rodný jazyk' },
]

const SWISS_PERMITS: WookyChoiceOption[] = [
  { value: 'EU/EFTA — bez omezení', label: 'EU / EFTA občan', hint: 'CZ, SK, PL atd. — bez omezení' },
  { value: 'B (krátkodobý pobyt)', label: 'Povolení B', hint: 'Roční, prodlužitelný' },
  { value: 'C (trvalý pobyt)', label: 'Povolení C', hint: 'Trvalý pobyt' },
  { value: 'L (krátkodobý)', label: 'Povolení L', hint: 'Do 1 roku' },
  { value: 'G (pendler)', label: 'Povolení G', hint: 'Příhraniční práce' },
  { value: 'F (předběžně přijat)', label: 'Povolení F', hint: 'Předběžné přijetí' },
  { value: 'Čekám na vyřízení', label: 'Čekám na vyřízení', hint: 'Žádost běží' },
  { value: 'Zatím nemám', label: 'Zatím nemám', hint: 'Hledám zaměstnavatele co zařídí' },
]

const DRIVING_LICENSES: WookyChoiceOption[] = [
  { value: 'B', label: 'B — osobní auto' },
  { value: 'C', label: 'C — nákladní > 3,5 t' },
  { value: 'C+E', label: 'C+E — souprava' },
  { value: 'D', label: 'D — autobus' },
  { value: 'A', label: 'A — motorka' },
  { value: 'T', label: 'T — traktor' },
  { value: 'vlastní auto', label: 'Vlastní auto' },
]

const SWISS_CANTONS: WookyChoiceOption[] = [
  { value: 'Kdekoliv', label: '🇨🇭 Kdekoliv ve Švýcarsku' },
  { value: 'Zürich', label: 'Curych (ZH)' },
  { value: 'Bern', label: 'Bern (BE)' },
  { value: 'Luzern', label: 'Lucern (LU)' },
  { value: 'Uri', label: 'Uri (UR)' },
  { value: 'Schwyz', label: 'Schwyz (SZ)' },
  { value: 'Obwalden', label: 'Obwalden (OW)' },
  { value: 'Nidwalden', label: 'Nidwalden (NW)' },
  { value: 'Glarus', label: 'Glarus (GL)' },
  { value: 'Zug', label: 'Zug (ZG)' },
  { value: 'Fribourg', label: 'Fribourg (FR)' },
  { value: 'Solothurn', label: 'Solothurn (SO)' },
  { value: 'Basel-Stadt', label: 'Basilej-město (BS)' },
  { value: 'Basel-Landschaft', label: 'Basilej-venkov (BL)' },
  { value: 'Schaffhausen', label: 'Schaffhausen (SH)' },
  { value: 'Appenzell A.', label: 'Appenzell A. (AR)' },
  { value: 'Appenzell I.', label: 'Appenzell I. (AI)' },
  { value: 'St. Gallen', label: 'St. Gallen (SG)' },
  { value: 'Graubünden', label: 'Graubünden (GR)' },
  { value: 'Aargau', label: 'Aargau (AG)' },
  { value: 'Thurgau', label: 'Thurgau (TG)' },
  { value: 'Ticino', label: 'Ticino (TI)' },
  { value: 'Vaud', label: 'Vaud (VD)' },
  { value: 'Wallis', label: 'Wallis (VS)' },
  { value: 'Neuchâtel', label: 'Neuchâtel (NE)' },
  { value: 'Genève', label: 'Ženeva (GE)' },
  { value: 'Jura', label: 'Jura (JU)' },
]

const NATIONALITIES: WookyChoiceOption[] = [
  { value: 'Česká', label: '🇨🇿 Česká' },
  { value: 'Slovenská', label: '🇸🇰 Slovenská' },
  { value: 'Polská', label: '🇵🇱 Polská' },
  { value: 'Ukrajinská', label: '🇺🇦 Ukrajinská' },
  { value: 'Rumunská', label: '🇷🇴 Rumunská' },
  { value: 'Bulharská', label: '🇧🇬 Bulharská' },
  { value: 'Maďarská', label: '🇭🇺 Maďarská' },
  { value: 'Chorvatská', label: '🇭🇷 Chorvatská' },
  { value: 'Srbská', label: '🇷🇸 Srbská' },
  { value: 'Italská', label: '🇮🇹 Italská' },
  { value: 'Portugalská', label: '🇵🇹 Portugalská' },
  { value: 'Španělská', label: '🇪🇸 Španělská' },
  { value: 'Albánská', label: '🇦🇱 Albánská' },
  { value: 'Severomakedonská', label: '🇲🇰 Severomakedonská' },
  { value: 'Bosna a Hercegovina', label: '🇧🇦 Bosna a Hercegovina' },
  { value: 'Turecká', label: '🇹🇷 Turecká' },
  { value: 'Vietnamská', label: '🇻🇳 Vietnamská' },
  { value: 'Filipínská', label: '🇵🇭 Filipínská' },
  { value: 'Jiná', label: 'Jiná' },
]

const INDUSTRIES: WookyChoiceOption[] = [
  { value: 'Logistika a sklad', label: '📦 Logistika a sklad' },
  { value: 'Gastronomie', label: '🍽️ Gastronomie a HoReCa' },
  { value: 'Stavba', label: '🏗️ Stavba' },
  { value: 'Doprava', label: '🚚 Doprava' },
  { value: 'Výroba', label: '🏭 Výroba' },
  { value: 'Péče a zdravotnictví', label: '🏥 Péče a zdravotnictví' },
  { value: 'Úklid a údržba', label: '🧹 Úklid a údržba' },
  { value: 'Zemědělství', label: '🌾 Zemědělství' },
  { value: 'Maloobchod', label: '🛒 Maloobchod' },
  { value: 'Bezpečnost', label: '🛡️ Bezpečnost' },
  { value: 'Administrativa', label: '📋 Administrativa' },
  { value: 'IT', label: '💻 IT' },
  { value: 'Jiné', label: 'Jiné' },
]

const LANGUAGE_OPTIONS = [
  'Angličtina',
  'Němčina',
  'Italština',
  'Francouzština',
  'Polština',
  'Ukrajinština',
  'Ruština',
  'Rumunština',
  'Bulharština',
  'Maďarština',
  'Albánština',
  'Srbština',
  'Chorvatština',
  'Slovinština',
  'Portugalština',
  'Španělština',
  'Turečtina',
  'Vietnamština',
  'Filipínština',
  'Slovenština',
  'Čeština',
]

// Vsechna pole, ktera Wooky umi pomoct vyplnit/upravit.
// Poradi = poradi v field pickeru (groupy podle sekce).
export const WOOKY_FIELDS: WookyFieldMeta[] = [
  // ===== Osobni udaje =====
  {
    key: 'full_name',
    label: 'Jméno a příjmení',
    icon: '👤',
    section: 'osobni-udaje',
    kind: 'simple',
    prompt: 'Začneme jménem — jak ti říkat?',
    example: 'Václav Kočka',
    valuePitch: 'Objeví se na tvém CV, v každém motivačním dopise a v podpisu Smart Apply e-mailů. Nejdůležitější pole celého profilu.',
  },
  {
    key: 'telefon',
    label: 'Telefon',
    icon: '📞',
    section: 'osobni-udaje',
    kind: 'simple',
    prompt: 'Telefonní číslo, na kterém tě může zaměstnavatel zastihnout.',
    example: '+41 79 123 45 67',
    valuePitch: 'Kontakt na CV. Použije se i v žádostech o bydlení a v Smart Apply e-mailech.',
  },
  {
    key: 'email',
    label: 'Kontaktní e-mail',
    icon: '✉️',
    section: 'osobni-udaje',
    kind: 'simple',
    prompt: 'E-mail, který uvedeš na CV (může se lišit od přihlašovacího).',
    example: 'jan.novak@example.com',
    valuePitch: 'Bude na CV jako kontakt. Přihlašovací e-mail (do Wokeru) se tím nemění.',
  },
  {
    key: 'nationality',
    label: 'Národnost',
    icon: '🌍',
    section: 'osobni-udaje',
    kind: 'choice',
    options: NATIONALITIES,
    multi: false,
    customAllowed: false,
    prompt: 'Vyber svou národnost.',
    valuePitch: 'Zaměstnavatelé to chtějí vědět kvůli povolení k práci. Objeví se v motivačních dopisech.',
  },
  {
    key: 'adresa',
    label: 'Adresa',
    icon: '🏠',
    section: 'osobni-udaje',
    kind: 'simple',
    prompt: 'Aktuální adresa — kde teď bydlíš (CH nebo domov).',
    example: 'Bahnhofstrasse 12, 8001 Curych',
    valuePitch: 'Bude na CV a v žádostech o bydlení. Stačí město a kanton, nemusíš dávat přesnou ulici.',
  },
  {
    key: 'ridicky_prukaz',
    label: 'Řidičský průkaz',
    icon: '🚗',
    section: 'osobni-udaje',
    kind: 'choice',
    options: DRIVING_LICENSES,
    multi: true,
    customAllowed: false,
    prompt: 'Vyber všechny skupiny, které máš (i zda máš vlastní auto).',
    valuePitch: 'Velké plus pro logistiku, stavbu, péči. Objeví se v CV i motivačních dopisech.',
  },

  // ===== Kariera =====
  {
    key: 'obor',
    label: 'Obor',
    icon: '🏭',
    section: 'kariera',
    kind: 'choice',
    options: INDUSTRIES,
    multi: false,
    customAllowed: true,
    prompt: 'V jakém oboru pracuješ nebo chceš pracovat?',
    valuePitch: 'Pomůže nám hledat ti relevantní nabídky. Použijeme to i v záhlaví CV.',
  },
  {
    key: 'pozice',
    label: 'Cílová pozice',
    icon: '🎯',
    section: 'kariera',
    kind: 'simple',
    prompt: 'Na jakou pozici se hlásíš nebo jaká tě baví?',
    example: 'Skladník / Logistik',
    valuePitch: 'Bude jako "obor" v záhlaví CV. Podle ní ti hledáme nabídky.',
  },
  {
    key: 'zkusenosti',
    label: 'Pracovní zkušenosti',
    icon: '💼',
    section: 'kariera',
    kind: 'expand',
    prompt: 'Stačí mi to říct rámcově — kde, kdy, co. Já to pak rozšířím do profesionálního jazyka.',
    example: '3 roky logistika ve Zlíně, řízení VZV. Pak rok montáž ve fabrice.',
    valuePitch: 'Tohle je srdce tvého CV. Když mi dáš základ, rozšířím to do bullet pointů, které čekají švýcarské HR. Použije se v každém CV a motivačním dopise.',
    expansionInstruction: `Rozšíř uživatelův vstup do 3-5 profesionálních bullet pointů v češtině pro švýcarské CV.
Použij silná akční slovesa (zajišťoval, koordinoval, obsluhoval, řídil).
KRITICKY DULEŽITÉ: Nikdy nepřidávej fakta která uživatel nezmínil. Pokud řekl "řízení VZV", nepřidávej "skupina B" pokud to nezmínil. Pokud řekl "3 roky logistika", neuváděj konkrétní zaměstnavatele.
Jen profesionálně přeformuluj + doplň běžné kontextové detaily (lokace, povaha práce) které logicky plynou z toho co řekl.`,
  },
  {
    key: 'vzdelani',
    label: 'Vzdělání',
    icon: '🎓',
    section: 'kariera',
    kind: 'expand',
    prompt: 'Nejvyšší dosažené vzdělání + obor. Stačí stručně, doplním.',
    example: 'SOU dopravní, opravář motorových vozidel, 2018',
    valuePitch: 'Objeví se v sekci Vzdělání tvého CV. Důležité pro pozice kde se vyžaduje formální kvalifikace.',
    expansionInstruction: `Rozšíř vzdělání uživatele do CV-friendly formátu pro švýcarský trh. Formát: "Stupeň + obor, instituce (volitelně město), rok ukončení".
Nikdy nedoplňuj jméno školy ani specifický rok pokud uživatel neuvedl. Jen normalizuj jeho vstup do profesionální podoby.`,
  },
  {
    key: 'dovednosti',
    label: 'Dovednosti',
    icon: '⚡',
    section: 'kariera',
    kind: 'expand',
    prompt: 'Co umíš? Stroje, nástroje, jazyky programů, soft skills...',
    example: 'VZV, SAP, MS Office, řidičák B, němčina',
    valuePitch: 'Zaměstnavatelé filtrují podle dovedností. Bude v CV jako seznam i v motivačních dopisech.',
    expansionInstruction: `Rozšíř seznam dovedností do CV-friendly podoby pro švýcarský trh.
Mix hard skills + soft skills + jazyky + certifikáty.
Žádné vymýšlení specifik (verze softwaru, čísla certifikátů, úrovně B2/C1 pokud user neuvedl).
Pokud user napsal "VZV", ponech "obsluha vysokozdvižného vozíku". Pokud "MS Office", expanduj na "MS Office (Word, Excel, Outlook)" — bezpečná expanze.
Vrať jako seznam oddělený čárkami.`,
  },
  {
    key: 'nemcina_uroven',
    label: 'Úroveň němčiny',
    icon: '🇨🇭',
    section: 'kariera',
    kind: 'choice',
    options: CEFR_LEVELS,
    multi: false,
    customAllowed: false,
    prompt: 'Jak na tom jsi s němčinou?',
    valuePitch: 'Kritické pro Švýcarsko. Použije se v CV a my podle toho vybíráme nabídky.',
  },
  {
    key: 'dalsi_jazyky',
    label: 'Další jazyky',
    icon: '🗣️',
    section: 'kariera',
    kind: 'languages',
    languageOptions: LANGUAGE_OPTIONS,
    levelOptions: CEFR_LEVELS,
    prompt: 'Které další jazyky ovládáš? Můžeš přidat víc.',
    valuePitch: 'Plus pro mnoho pozic — hotely, cestovní ruch, mezinárodní firmy. Objeví se v CV.',
  },

  // ===== Cil =====
  {
    key: 'preferovany_kanton',
    label: 'Preferovaný kanton',
    icon: '📍',
    section: 'cil',
    kind: 'choice',
    options: SWISS_CANTONS,
    multi: false,
    customAllowed: false,
    prompt: 'Ve kterém kantonu chceš pracovat?',
    valuePitch: 'Podle toho ti hledáme nabídky a bydlení.',
  },
  {
    key: 'income_expected',
    label: 'Očekávaný plat',
    icon: '💰',
    section: 'cil',
    kind: 'simple',
    prompt: 'Kolik CHF si chceš vydělat měsíčně (brutto)?',
    example: '5000',
    valuePitch: 'Použijeme jen interně k filtrování nabídek. Nikam se neposílá.',
  },
  {
    key: 'work_permit_status',
    label: 'Pracovní povolení',
    icon: '🪪',
    section: 'cil',
    kind: 'choice',
    options: SWISS_PERMITS,
    multi: false,
    customAllowed: false,
    prompt: 'Jaké máš povolení nebo na jakém pracuješ?',
    valuePitch: 'Zaměstnavatelé to chtějí vědět hned. Objeví se v motivačních dopisech.',
  },
  {
    key: 'employer_current',
    label: 'Současný zaměstnavatel',
    icon: '🏢',
    section: 'cil',
    kind: 'simple',
    prompt: 'Kde teď pracuješ (pokud někde)?',
    example: 'DHL Logistics, Curych',
    valuePitch: 'Volitelné. Použijeme pro lepší formulaci v motivačním dopise.',
  },
]

export function wookyField(key: string): WookyFieldMeta | undefined {
  return WOOKY_FIELDS.find((f) => f.key === key)
}

export const WOOKY_FIELDS_BY_SECTION = {
  'osobni-udaje': WOOKY_FIELDS.filter((f) => f.section === 'osobni-udaje'),
  'kariera': WOOKY_FIELDS.filter((f) => f.section === 'kariera'),
  'cil': WOOKY_FIELDS.filter((f) => f.section === 'cil'),
}
